import type { Channel, Comment, Short, Video } from "./types";

const pic = (seed: string, w = 640, h = 360) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`;
const av = (seed: string) => `https://picsum.photos/seed/${seed}/96/96`;

export const channels: Channel[] = [
  {
    id: "ch-codeweva",
    name: "CodeWithEva",
    handle: "@codewitheva",
    avatar: av("codeweva"),
    subscribers: "128万",
    verified: true,
  },
  {
    id: "ch-pixelquest",
    name: "Pixel Quest Gaming",
    handle: "@pixelquest",
    avatar: av("pixelquest"),
    subscribers: "84.2万",
    verified: true,
  },
  {
    id: "ch-lofi",
    name: "Lo-Fi Garden",
    handle: "@lofigarden",
    avatar: av("lofigarden"),
    subscribers: "341万",
    verified: true,
  },
  {
    id: "ch-kitchen",
    name: "Kitchen Lab",
    handle: "@kitchenlab",
    avatar: av("kitchenlab"),
    subscribers: "61.4万",
  },
  {
    id: "ch-wander",
    name: "Wander Japan",
    handle: "@wanderjapan",
    avatar: av("wanderjp"),
    subscribers: "212万",
    verified: true,
  },
  {
    id: "ch-cosmos",
    name: "Curious Cosmos",
    handle: "@curiouscosmos",
    avatar: av("cosmos"),
    subscribers: "562万",
    verified: true,
  },
  {
    id: "ch-move",
    name: "Daily Move Fitness",
    handle: "@dailymove",
    avatar: av("dailymove"),
    subscribers: "42.3万",
  },
  {
    id: "ch-tech-news",
    name: "Tech Threads News",
    handle: "@techthreads",
    avatar: av("techthreads"),
    subscribers: "98.7万",
    verified: true,
  },
  {
    id: "ch-standup",
    name: "Stand-Up Tonight",
    handle: "@standuptonight",
    avatar: av("standup"),
    subscribers: "31.2万",
  },
  {
    id: "ch-diy",
    name: "Make It Yourself",
    handle: "@makeityourself",
    avatar: av("diy"),
    subscribers: "182万",
    verified: true,
  },
];

export const videos: Video[] = [
  {
    id: "v0",
    title: "🔴 LIVE: Tokyo Dev Conference 2026 - Main Stage",
    thumbnail: pic("live-stage"),
    duration: "LIVE",
    views: "8,421 人が視聴中",
    uploadedAt: "配信中",
    channelId: "ch-tech-news",
    description:
      "Tokyo Dev Conference 2026 のメインステージを生中継。基調講演、パネルディスカッション、最新フレームワークの発表をお届けします。",
    likes: "3.2万",
    category: "Live",
  },
  {
    id: "v1",
    title: "Next.js 16 で Cache Components を使いこなす【完全ガイド】",
    thumbnail: pic("nextjs-cache"),
    duration: "18:42",
    views: "284万 回視聴",
    uploadedAt: "2 日前",
    channelId: "ch-codeweva",
    description:
      "Next.js 16 の目玉機能、Cache Components の使い方を実例で解説。use cache ディレクティブ、cacheLife、cacheTag、PPR との関係性まで一気に学べます。",
    likes: "12万",
    category: "Tech",
  },
  {
    id: "v2",
    title: "深夜の作業BGM ☕ Lo-Fi Beats to Focus / Sleep / Relax",
    thumbnail: pic("lofi-night"),
    duration: "3:48:21",
    views: "8,124万 回視聴",
    uploadedAt: "1 年前",
    channelId: "ch-lofi",
    description:
      "深夜の作業や勉強に最適な、心地よいローファイビートを4時間ノンストップでお届けします。コメント欄でリクエストもどうぞ。",
    likes: "62万",
    category: "Music",
  },
  {
    id: "v3",
    title: "失敗しない！至高のカルボナーラの作り方 - プロの技3選",
    thumbnail: pic("carbonara"),
    duration: "12:08",
    views: "1,142万 回視聴",
    uploadedAt: "3 週間前",
    channelId: "ch-kitchen",
    description:
      "卵が固まらない火加減、ローマ流の塩バランス、麺の茹で方。プロの料理人から学んだ3つのコツを完全公開します。",
    likes: "94万",
    category: "Cooking",
  },
  {
    id: "v4",
    title: "京都・早朝の嵐山を歩く 🍃 誰もいない竹林の小径 4K",
    thumbnail: pic("kyoto-bamboo"),
    duration: "21:32",
    views: "382万 回視聴",
    uploadedAt: "5 日前",
    channelId: "ch-wander",
    description:
      "観光客が訪れる前の朝5時、霧に包まれた嵐山の竹林を散策します。鳥のさえずりと風の音をお楽しみください。",
    likes: "21万",
    category: "Travel",
  },
  {
    id: "v5",
    title: "ELDEN RING NIGHTREIGN 初見プレイ #1 - 第一夜は失敗だらけ",
    thumbnail: pic("elden-ring"),
    duration: "1:42:08",
    views: "2,104万 回視聴",
    uploadedAt: "5 日前",
    channelId: "ch-pixelquest",
    description:
      "FromSoftware の最新作 ELDEN RING NIGHTREIGN を初見でプレイ。第一夜の生存記録をお届け。",
    likes: "184万",
    category: "Gaming",
  },
  {
    id: "v6",
    title: "Synthwave Drive 🌃 80s Retro Mix - 60 minutes",
    thumbnail: pic("synthwave"),
    duration: "1:02:34",
    views: "418万 回視聴",
    uploadedAt: "2 週間前",
    channelId: "ch-lofi",
    description: "夜のドライブにぴったりの 80s シンセウェーブを1時間ノンストップで。",
    likes: "26万",
    category: "Music",
  },
  {
    id: "v7",
    title: "なぜ宇宙は加速膨張するのか？JWST が明かした衝撃の事実",
    thumbnail: pic("cosmos-jwst"),
    duration: "18:55",
    views: "3,287万 回視聴",
    uploadedAt: "1 週間前",
    channelId: "ch-cosmos",
    description:
      "ジェイムズ・ウェッブ宇宙望遠鏡と DESI の最新観測から、ダークエネルギーの正体に迫ります。",
    likes: "247万",
    category: "Science",
  },
  {
    id: "v8",
    title: "朝5分でできる！全身を目覚めさせるストレッチルーティン",
    thumbnail: pic("stretch"),
    duration: "5:42",
    views: "892万 回視聴",
    uploadedAt: "4 日前",
    channelId: "ch-move",
    description:
      "ベッドから起き上がる前にできる、肩こり・腰痛予防のストレッチを5分で。",
    likes: "58万",
    category: "Fitness",
  },
  {
    id: "v9",
    title: "TypeScript 7.0 のすべて - ネイティブ実装で10倍速くなった理由",
    thumbnail: pic("ts7"),
    duration: "22:17",
    views: "498万 回視聴",
    uploadedAt: "3 日前",
    channelId: "ch-tech-news",
    description:
      "Microsoft が発表した TypeScript ネイティブ実装。なぜ10倍速くなったのか、技術的な背景を解説します。",
    likes: "31万",
    category: "Tech",
  },
  {
    id: "v10",
    title: "北海道・冬の絶景駅10選 ❄️ 雪に閉ざされた廃線の物語",
    thumbnail: pic("hokkaido-train"),
    duration: "27:32",
    views: "1,184万 回視聴",
    uploadedAt: "2 か月前",
    channelId: "ch-wander",
    description:
      "もう列車は来ない、雪原に佇む駅たち。北海道の鉄道遺産を巡るドキュメンタリー。",
    likes: "67万",
    category: "Travel",
  },
  {
    id: "v11",
    title: "10分で完成！本格四川風 麻婆豆腐の作り方",
    thumbnail: pic("mapo"),
    duration: "9:48",
    views: "742万 回視聴",
    uploadedAt: "1 週間前",
    channelId: "ch-kitchen",
    description:
      "本場で修行したシェフ直伝の麻婆豆腐レシピ。家庭で再現できる火入れの黄金比をお見せします。",
    likes: "44万",
    category: "Cooking",
  },
  {
    id: "v12",
    title: "【100日サバイバル】Minecraft 1.22 で巨大都市を建設してみた",
    thumbnail: pic("minecraft-city"),
    duration: "45:22",
    views: "5,824万 回視聴",
    uploadedAt: "1 か月前",
    channelId: "ch-pixelquest",
    description:
      "ハードコアモードで100日サバイバルし、完成した巨大都市の全貌を公開します。",
    likes: "412万",
    category: "Gaming",
  },
];

const SAMPLES: Record<string, string> = {
  bunny: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
  ed: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
  sintel: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
  escapes: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
  fun: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
  joy: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
  meltdowns: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
  steel: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
  blazes: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
  subaru: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
};

export const shorts: Short[] = [
  {
    id: "s1",
    title: "1秒でわかる Tailwind v4 の新機能",
    thumbnail: pic("short-tailwind", 540, 960),
    src: SAMPLES.bunny,
    views: "284万",
    bigText: "1秒で\nわかる",
    accent: "yellow",
    tag: "#tech",
    channel: "CodeWithEva",
    channelAvatar: av("codeweva"),
    likes: "42万",
    comments: "1.2万",
  },
  {
    id: "s2",
    title: "猫が箱に入るまでの15秒",
    thumbnail: pic("short-cat", 540, 960),
    src: SAMPLES.fun,
    views: "841万",
    bigText: "本気の\n15秒",
    accent: "white",
    tag: "🐈",
    channel: "Daily Cat Clips",
    channelAvatar: av("cat-channel"),
    likes: "94万",
    comments: "3.1万",
  },
  {
    id: "s3",
    title: "プロのトマトの切り方",
    thumbnail: pic("short-tomato", 540, 960),
    src: SAMPLES.escapes,
    views: "312万",
    bigText: "プロの\n包丁さばき",
    accent: "red",
    tag: "🔪",
    channel: "Kitchen Lab",
    channelAvatar: av("kitchenlab"),
    likes: "18万",
    comments: "8,420",
  },
  {
    id: "s4",
    title: "東京タワーから見た夕日 🌇",
    thumbnail: pic("short-tokyo", 540, 960),
    src: SAMPLES.joy,
    views: "612万",
    bigText: "東京の\n夕暮れ",
    accent: "cyan",
    tag: "4K",
    channel: "Wander Japan",
    channelAvatar: av("wanderjp"),
    likes: "38万",
    comments: "1.8万",
  },
  {
    id: "s5",
    title: "1分間プランクチャレンジ",
    thumbnail: pic("short-plank", 540, 960),
    src: SAMPLES.meltdowns,
    views: "94万",
    bigText: "1分\n体幹",
    accent: "lime",
    tag: "#fitness",
    channel: "Daily Move",
    channelAvatar: av("dailymove"),
    likes: "5.2万",
    comments: "1,840",
  },
  {
    id: "s6",
    title: "Vim マクロでリファクタ",
    thumbnail: pic("short-vim", 540, 960),
    src: SAMPLES.ed,
    views: "28万",
    bigText: "知らないと\n損",
    accent: "yellow",
    tag: "#code",
    channel: "CodeWithEva",
    channelAvatar: av("codeweva"),
    likes: "1.8万",
    comments: "924",
  },
  {
    id: "s7",
    title: "ラテアートの作り方",
    thumbnail: pic("short-latte", 540, 960),
    src: SAMPLES.blazes,
    views: "184万",
    bigText: "プロ直伝\nラテアート",
    accent: "white",
    tag: "☕",
    channel: "Kitchen Lab",
    channelAvatar: av("kitchenlab"),
    likes: "12万",
    comments: "4,210",
  },
  {
    id: "s8",
    title: "渋谷スクランブル 4K",
    thumbnail: pic("short-shibuya", 540, 960),
    src: SAMPLES.subaru,
    views: "421万",
    bigText: "渋谷の朝",
    accent: "white",
    tag: "4K",
    channel: "Wander Japan",
    channelAvatar: av("wanderjp"),
    likes: "26万",
    comments: "9,820",
  },
  {
    id: "s9",
    title: "Minecraft 1分建築 - 隠し階段",
    thumbnail: pic("short-mc", 540, 960),
    src: SAMPLES.sintel,
    views: "1,284万",
    bigText: "1分で\n建築",
    accent: "red",
    tag: "#minecraft",
    channel: "Pixel Quest Gaming",
    channelAvatar: av("pixelquest"),
    likes: "82万",
    comments: "5.1万",
  },
  {
    id: "s10",
    title: "5分でできる卵チャーハン",
    thumbnail: pic("short-fried", 540, 960),
    src: SAMPLES.steel,
    views: "924万",
    bigText: "5分で\n本格中華",
    accent: "yellow",
    tag: "🍳",
    channel: "Kitchen Lab",
    channelAvatar: av("kitchenlab"),
    likes: "62万",
    comments: "2.4万",
  },
];

export const comments: Comment[] = [
  {
    id: "c0",
    author: "CodeWithEva",
    avatar: av("codeweva"),
    timeAgo: "1 週間前 (編集済み)",
    text: "ご視聴ありがとうございます！動画の続編を来週公開予定です。チャンネル登録と通知ベルでお待ちください 🔔",
    likes: "1.2万",
    replies: 184,
    pinned: true,
    isCreator: true,
    verified: true,
  },
  {
    id: "c1",
    author: "@haruto_dev",
    avatar: av("user-haruto"),
    timeAgo: "2 時間前",
    text: "この説明、公式ドキュメントより分かりやすい...！やっと腑に落ちました。",
    likes: "1,284",
    replies: 24,
    creatorHearted: true,
  },
  {
    id: "c2",
    author: "@miyu_codes",
    avatar: av("user-miyu"),
    timeAgo: "5 時間前",
    text: "8:42 の図解、めちゃくちゃ分かりやすい。チームで共有させてください！",
    likes: "542",
    replies: 8,
  },
  {
    id: "c3",
    author: "@tk_engineer",
    avatar: av("user-tk"),
    timeAgo: "8 時間前",
    text: "自分も同じところでハマっていました。早めにこの動画見ておきたかった〜",
    likes: "318",
  },
  {
    id: "c4",
    author: "@nana_frontend",
    avatar: av("user-nana"),
    timeAgo: "12 時間前",
    text: "Suspense 境界の話、レビューで指摘されたばかりなのでタイムリーすぎる。",
    likes: "412",
    replies: 6,
  },
  {
    id: "c5",
    author: "@codewith_sora",
    avatar: av("user-sora"),
    timeAgo: "1 日前",
    text: "10分でこのクオリティはちょっとおかしい（褒めてる）",
    likes: "892",
    replies: 14,
  },
  {
    id: "c6",
    author: "@yuki_react",
    avatar: av("user-yuki"),
    timeAgo: "1 日前",
    text: "次は cacheTag と updateTag の関係を深掘りしてほしいです 🙏",
    likes: "267",
  },
];

export const filterChips = [
  "すべて",
  "音楽",
  "ゲーム",
  "ライブ",
  "プログラミング",
  "料理",
  "旅行",
  "科学",
  "ニュース",
  "ポッドキャスト",
  "Lo-Fi",
  "JavaScript",
  "TypeScript",
  "Next.js",
  "Minecraft",
  "ELDEN RING",
  "ミックスリスト",
  "最近アップロードされた動画",
  "視聴済み",
];

export function getChannel(id: string) {
  return channels.find((c) => c.id === id);
}

export function getVideo(id: string) {
  return videos.find((v) => v.id === id);
}

export function isChannelLive(id: string) {
  return videos.some((v) => v.channelId === id && v.duration === "LIVE");
}
